AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: The lambdas for supporter reminders

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: membership-dist
  SecurityGroupToAccessPostgres:
    Description: Security group to access the RDS instance
    Type: String
  VpcSubnets:
    Description: Subnets for RDS access
    Type: List<AWS::EC2::Subnet::Id>
  CertificateArn:
    Description: ARN of the certificate
    Type: String
  DatalakeBucket:
    Description: Bucket to upload data for ingestion into BigQuery
    Type: String

Mappings:
  StageMap:
    CODE:
      DomainName: reminders-code.support.guardianapis.com
      CorsOrigin: "'*'"
    PROD:
      DomainName: reminders.support.guardianapis.com
      CorsOrigin: "'*'"

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Globals:
  Api:
    Cors:
      AllowOrigin: !FindInMap [ StageMap, !Ref Stage, CorsOrigin ]
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'*'"

Resources:

  CreateReminderSignupLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub support-reminders-create-reminder-signup-${Stage}
      Description: A lambda for creating support reminders
      Runtime: nodejs10.x
      Handler: create-reminder-signup/lambda/lambda.handler
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/support-reminders/support-reminders.zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupToAccessPostgres
        SubnetIds: !Ref VpcSubnets
      Policies:
        # there are some extra permissions needed for a lambda to access resources in a VPC
        # https://docs.aws.amazon.com/lambda/latest/dg/vpc.html
        # hence this role rather than BasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParametersByPath
              - ssm:GetParameter
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/support-reminders/db-config/${Stage}
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/support-reminders/idapi/${Stage}/*
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/remind-me'
            Method: post

  NextRemindersLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub support-reminders-next-reminders-${Stage}
      Description: A lambda for getting next reminders data
      Runtime: nodejs10.x
      Handler: next-reminders/lambda/lambda.handler
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          Stage: !Ref Stage
          Bucket: !Ref DatalakeBucket
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/support-reminders/support-reminders.zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupToAccessPostgres
        SubnetIds: !Ref VpcSubnets
      Policies:
        # there are some extra permissions needed for a lambda to access resources in a VPC
        # https://docs.aws.amazon.com/lambda/latest/dg/vpc.html
        # hence this role rather than BasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParametersByPath
              - ssm:GetParameter
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/support-reminders/db-config/${Stage}
        - Statement:
            Effect: Allow
            Action:
            - s3:PutObject
            - s3:PutObjectAcl
            Resource:
            - !Sub arn:aws:s3:::${DatalakeBucket}
            - !Sub arn:aws:s3:::${DatalakeBucket}/*

  DomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      RegionalCertificateArn: # only for *.support.guardianapis.com
        !Ref CertificateArn
      DomainName: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      EndpointConfiguration:
        Types:
          - REGIONAL

  BasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      RestApiId: !Ref ServerlessRestApi # auto generated by the Transform
      DomainName: !Ref DomainName
      Stage: !Sub Prod
    DependsOn: ServerlessRestApiProdStage # auto generated by the Transform

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: support.guardianapis.com.
      Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
      Comment: !Sub CNAME for contributions reminders endpoint ${Stage}
      Type: CNAME
      TTL: '120'
      ResourceRecords:
        - !GetAtt [ DomainName, RegionalDomainName ]
