name: Build support-reminders

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  support_reminders_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.event.pull_request.head.repo.owner.login == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: support-reminders build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node for CDK
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: cdk/yarn.lock

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      # Required by sbt riffRaffUpload
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Build and upload to RiffRaff
        run: |
          export LAST_TEAMCITY_BUILD=6000
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          yarn package
