name: Build support-reminders

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  support_reminders_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.event.pull_request.head.repo.owner.login == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: support-reminders build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout repo
        uses: actions/checkout@v2

      # (Respects .nvmrc)
      - name: Setup Node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            cdk/yarn.lock

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      - name: Build and upload to RiffRaff
        run: |
          export LAST_TEAMCITY_BUILD=10000
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          yarn package
