name: Build support-reminders

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  CI:
    if: github.repository_owner == 'guardian'
    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    name: support-reminders build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Env
        run: env

      - name: Checkout
        uses: actions/checkout@v6.0.3

      - run: npm install --global corepack@0.31.0
        shell: bash

      - run: corepack enable
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: test install build
        run: |
          pnpm clean
          pnpm install
          pnpm lint
          pnpm run build

      - name: Run unit tests
        run: pnpm test --silent
        env:
          TEST_DB_URL: postgresql://localhost/postgres
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: postgres

      - name: production install, build
        run: |
          pnpm clean
          pnpm install --production
          pnpm run build

      - name: Zip target directory contents
        run: zip -r ../support-reminders.zip ./*
        working-directory: ./target

      - name: Pnpm (CDK)
        working-directory: cdk
        run: |
          pnpm install
          pnpm tsc
          pnpm lint
          pnpm test

      - name: Pnpm synth (CDK)
        working-directory: cdk
        run: pnpm synth

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4.3.0
        with:
          app: support-reminders
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: ./riff-raff.yaml
          contentDirectories: |
            support-reminders-cloudformation:
              - ./cdk/cdk.out/SupportReminders-CODE.template.json
              - ./cdk/cdk.out/SupportReminders-PROD.template.json
            support-reminders:
              - ./support-reminders.zip
