name: Build support-reminders

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  CI:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.event.pull_request.head.repo.owner.login == 'guardian' ||
          github.event_name == 'push')
    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read
    name: support-reminders build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './.nvmrc'
          cache: 'yarn'

      - name: Run script/ci.sh
        run: ./script/ci.sh

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: support-reminders
          configPath: ./riff-raff.yaml
          contentDirectories: |
            support-reminders-cloudformation:
              - ./cfn.yaml
            support-reminders:
              - ./support-reminders.zip



