name: Test Dependabot PRs

on:
  pull_request:

env:
  GU_SUPPORT_WORKERS_LOAD_S3_CONFIG: false

jobs:
  run_node_tests:
    if: github.actor == 'dependabot[bot]'
    name: test dependabot
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # ---- Logging ---- #
      - name: Env
        run: env

      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

      # ---- Setup ---- #
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install - support-reminders
        run: yarn
        working-directory: /

      - name: Install - CDK
        run: yarn
        working-directory: cdk

      # ---- Build ---- #
      - name: Build - support-reminders
        run: yarn run build
        working-directory: /


      - name: Build - CDK
        run: yarn run build
        working-directory: cdk

      # ---- Test ---- #
      - name: Test - support-reminders
        run: yarn run test
        working-directory: /
        env:
          TEST_DB_URL: postgresql://localhost/postgres
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: postgres

      - name: Test - CDK
        run: yarn run test
        working-directory: cdk




